# Generated by Django 3.0.4 on 2020-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('issue', models.IntegerField()),
                ('pages', models.CharField(max_length=500)),
                ('DOI', models.CharField(max_length=500)),
            ],
        ),
    ]
