# Generated by Django 3.0.4 on 2020-03-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper',
            new_name='Papers',
        ),
    ]
