# Generated by Django 3.0.4 on 2020-03-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20200312_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='DOI',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issue',
            field=models.IntegerField(null=True),
        ),
    ]
