# Generated by Django 3.0.4 on 2020-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20200312_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='DOI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
