# Generated by Django 4.2.4 on 2023-09-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
