# Generated by Django 4.2.4 on 2023-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('journal', models.TextField()),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('pages', models.CharField(max_length=500)),
                ('DOI', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
