# Generated by Django 4.2.4 on 2023-09-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_alter_image_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='agency',
        ),
    ]
