# Generated by Django 4.2.4 on 2023-09-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_alter_image_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='description',
        ),
    ]
