# Generated by Django 4.2.4 on 2023-09-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_remove_folder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='folder',
        ),
    ]
