# Generated by Django 4.2.4 on 2023-09-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_alter_image_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='folder',
        ),
        migrations.AddField(
            model_name='image',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.agency'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
