# Generated by Django 4.2.4 on 2023-09-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_image_folder'),
        ('WebApp', '0003_folder_image_folder'),
        ('WebApp', '0025_folder_remove_image_agency_image_folder'),
    ]

    operations = [
    ]
