# Generated by Django 4.2.4 on 2023-09-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_delete_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
