# Generated by Django 4.2.4 on 2023-09-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0030_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='foldername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
