# Generated by Django 4.2.4 on 2023-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0035_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='people_images/')),
            ],
        ),
    ]
