# Generated by Django 4.2.4 on 2023-09-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_peopletitle_alter_people_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopletitle',
            old_name='order',
            new_name='titleorder',
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.peopletitle'),
        ),
    ]
