# Generated by Django 4.2.4 on 2023-09-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0038_rename_order_peopletitle_titleorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('titleorder', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.people_title'),
        ),
        migrations.DeleteModel(
            name='PeopleTitle',
        ),
    ]
