# Generated by Django 4.2.4 on 2023-09-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0039_people_title_alter_people_title_delete_peopletitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('titleorder', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.title_people'),
        ),
    ]
