# Generated by Django 4.2.4 on 2023-09-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0041_delete_people_title_alter_people_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Title_People',
        ),
    ]
