# Generated by Django 4.2.4 on 2023-09-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0042_remove_people_title_delete_people_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People_Title',
        ),
    ]
