# Generated by Django 4.2.4 on 2023-09-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0043_delete_people_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('titleorder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.title_people')),
            ],
        ),
    ]
