# Generated by Django 4.1 on 2023-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0045_people_bio_people_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='cv',
            field=models.FileField(upload_to='cv_files/'),
        ),
    ]
